GestaoDeLaboratorios/Models/Computador.cs
namespace GestaoDeLaboratorios.Models
{
    public class Computador
    {
        public int Id { get; set; }
        public required string? Marca { get; set; }
        public string? Processador { get; set; }
        public string? PlacaMae { get; set; }
        public string? Memoria { get; set; }
        public string? HD { get; set; }
        public string? NumeroPatrimonio { get; set; }
        public DateTime DataCompra { get; set; }
    }
}

GestaoDeLaboratorios/Models/ErrorViewModel.cs
namespace GestaoDeLaboratorios.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GestaoDeLaboratorios/Controllers/ComputadorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestaoDeLaboratorios.DAL;
using GestaoDeLaboratorios.Models;

namespace GestaoDeLaboratorios.Controllers
{
    public class ComputadorsController : Controller
    {
        private readonly InfnetDbContext _context;

        public ComputadorsController(InfnetDbContext context)
        {
            _context = context;
        }

        // GET: Computadors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Computadores.ToListAsync());
        }

        // GET: Computadors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var computador = await _context.Computadores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (computador == null)
            {
                return NotFound();
            }

            return View(computador);
        }

        // GET: Computadors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Computadors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Marca,Processador,PlacaMae,Memoria,HD,NumeroPatrimonio,DataCompra")] Computador computador)
        {
            if (ModelState.IsValid)
            {
                _context.Add(computador);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(computador);
        }

        // GET: Computadors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var computador = await _context.Computadores.FindAsync(id);
            if (computador == null)
            {
                return NotFound();
            }
            return View(computador);
        }

        // POST: Computadors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Marca,Processador,PlacaMae,Memoria,HD,NumeroPatrimonio,DataCompra")] Computador computador)
        {
            if (id != computador.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(computador);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComputadorExists(computador.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(computador);
        }

        // GET: Computadors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var computador = await _context.Computadores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (computador == null)
            {
                return NotFound();
            }

            return View(computador);
        }

        // POST: Computadors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var computador = await _context.Computadores.FindAsync(id);
            if (computador != null)
            {
                _context.Computadores.Remove(computador);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComputadorExists(int id)
        {
            return _context.Computadores.Any(e => e.Id == id);
        }
    }
}

GestaoDeLaboratorios/Controllers/HomeController.cs
using GestaoDeLaboratorios.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GestaoDeLaboratorios.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GestaoDeLaboratorios/Views/Computadors/Create.cshtml
@model GestaoDeLaboratorios.Models.Computador

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Computador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Processador" class="control-label"></label>
                <input asp-for="Processador" class="form-control" />
                <span asp-validation-for="Processador" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlacaMae" class="control-label"></label>
                <input asp-for="PlacaMae" class="form-control" />
                <span asp-validation-for="PlacaMae" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Memoria" class="control-label"></label>
                <input asp-for="Memoria" class="form-control" />
                <span asp-validation-for="Memoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HD" class="control-label"></label>
                <input asp-for="HD" class="form-control" />
                <span asp-validation-for="HD" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroPatrimonio" class="control-label"></label>
                <input asp-for="NumeroPatrimonio" class="form-control" />
                <span asp-validation-for="NumeroPatrimonio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataCompra" class="control-label"></label>
                <input asp-for="DataCompra" class="form-control" />
                <span asp-validation-for="DataCompra" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestaoDeLaboratorios/Views/Computadors/Delete.cshtml
@model GestaoDeLaboratorios.Models.Computador

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Computador</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Processador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Processador)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlacaMae)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlacaMae)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Memoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Memoria)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HD)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HD)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroPatrimonio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroPatrimonio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataCompra)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataCompra)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GestaoDeLaboratorios/Views/Computadors/Details.cshtml
@model GestaoDeLaboratorios.Models.Computador

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Computador</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Processador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Processador)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlacaMae)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlacaMae)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Memoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Memoria)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HD)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HD)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroPatrimonio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroPatrimonio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataCompra)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataCompra)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GestaoDeLaboratorios/Views/Computadors/Edit.cshtml
@model GestaoDeLaboratorios.Models.Computador

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Computador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Processador" class="control-label"></label>
                <input asp-for="Processador" class="form-control" />
                <span asp-validation-for="Processador" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlacaMae" class="control-label"></label>
                <input asp-for="PlacaMae" class="form-control" />
                <span asp-validation-for="PlacaMae" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Memoria" class="control-label"></label>
                <input asp-for="Memoria" class="form-control" />
                <span asp-validation-for="Memoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HD" class="control-label"></label>
                <input asp-for="HD" class="form-control" />
                <span asp-validation-for="HD" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroPatrimonio" class="control-label"></label>
                <input asp-for="NumeroPatrimonio" class="form-control" />
                <span asp-validation-for="NumeroPatrimonio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataCompra" class="control-label"></label>
                <input asp-for="DataCompra" class="form-control" />
                <span asp-validation-for="DataCompra" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestaoDeLaboratorios/Views/Computadors/Index.cshtml
@model IEnumerable<GestaoDeLaboratorios.Models.Computador>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Processador)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlacaMae)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Memoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HD)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroPatrimonio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataCompra)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Processador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlacaMae)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Memoria)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HD)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroPatrimonio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataCompra)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

GestaoDeLaboratorios/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GestaoDeLaboratorios/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestaoDeLaboratorios</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestaoDeLaboratorios.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GestaoDeLaboratorios</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Computadors" asp-action="Index">Computadores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GestaoDeLaboratorios - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>